### ISSUE TITLE
Useless Error Message when a Bad Virtual Host name is passed to ConnectionFactory

### ISSUE THREAD

**Issue by danapsimer** [rabbitmq/rabbitmq-java-client#100]
Here is some code that reproduces the issue:

```groovy
package com.bluesoftdev.bug.rmq

import com.rabbitmq.client.Connection
import com.rabbitmq.client.ConnectionFactory

class RMQBadVHostNameConnectionError {

    static String host = 'localhost'
    static String username = 'cruise'
    static String password = 'cru1s3'
    static String vhost = '/cruise'

    public static void main(String[] args) {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setUsername(username);
        factory.setPassword(password);
        factory.setVirtualHost(vhost);
        factory.setHost(host);
        Connection conn = factory.newConnection();
        conn.close();
    }
}
```
the virutal host named in the "vhost" variable does not exist on my local RMQ.

Here is the useless error message that was returned:
```
java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:378)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:648)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:678)
	at com.rabbitmq.client.ConnectionFactory$newConnection$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.bluesoftdev.bug.rmq.RMQBadVHostNameConnectionError.main(RMQBadVHostNameConnectionError.groovy:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:361)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:226)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
	... 13 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:536)
	at java.lang.Thread.run(Thread.java:745)
```

There is no indication that the error was caused by the bad virtual host name.

**Comment by michaelklishin** [comment]
@danapsimer while I agree that the error message isn't particularly helpful, server log is, and "connection error" is not entirely unreasonable. Unfortunately there is no separate protocol method for this specific failure, so the client has no way of knowing if this was a missing vhost, lack of vhost permissions for the user, or something else.

Introducing a protocol extension is not a trivial undertaking: it involves updating many clients.

**Comment by michaelklishin** [comment]
Tagged with both `wontfix` and `no-decision` because this is not a client-specific issue: it needs a protocol extension, which may or may not be worth the gain. In any case, it belongs to rabbitmq-server.

**Comment by danapsimer** [comment]
I was worried that I was putting this in the wrong place because it seems that "EOF" could be the response from several types of errors and certainly does not give much feedback to the caller.  

However, A quick look at the code indicates that the error is occurring on the Open RPC.  Some indication of what RPC failed in the ShutdownSignalException might give enough information to point the user in the right direction.

**Comment by blasd** [comment]
Hello,
I encountered the same issue than reported here. The root cause seemed to be the vhost were '/cruise', while it should be 'cruise'. Previously reported here:
http://forum.spring.io/forum/spring-projects/integration/122318-rabbitmq-configuration-failing

Maybe the RabbitMQ could report this more explicitly?

**Comment by michaelklishin** [comment]
@blasd or maybe developers should properly [percent-escape URI segments](https://www.rabbitmq.com/uri-spec.html), just like any other data service requires.
