### ISSUE TITLE
NullPointerException during connection recovery

### ISSUE THREAD

**Issue by Fezz0** [rabbitmq/rabbitmq-java-client#107]
Hi, we've been experiencing strange exception in our app, which is built on top of apache camel 2.14.3 with ampq-client 3.3.4 (I know it's a bit old, but I haven't found any info about this issue, so I assume it relates to all versions). Here's exception that we are getting after some network failures:

26-11-2015 14:30:00.983 [pool-1-thread-24] ERROR ExtendedExceptionHandler: ExtendedExceptionHandler.handleConnectionRecoveryException(ExtendedExceptionHandler.java:110) - Caught an exception during connection recovery!:
java.net.SocketException: Connection reset
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:96)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
    at java.io.DataOutputStream.flush(DataOutputStream.java:106)
    at com.rabbitmq.client.impl.SocketFrameHandler.sendHeader(SocketFrameHandler.java:129)
    at com.rabbitmq.client.impl.SocketFrameHandler.sendHeader(SocketFrameHandler.java:134)
    at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:276)
    at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:36)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:388)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:360)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:48)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.shutdownCompleted(AutorecoveringConnection.java:345)
    at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:75)
    at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:572)
    at java.lang.Thread.run(Thread.java:662)
26-11-2015 14:30:24.960 [pool-2-thread-45] ERROR ExtendedExceptionHandler:ExtendedExceptionHandler.handleConnectionRecoveryException(ExtendedExceptionHandler.java:110) - Caught an exception during connection recovery!:
java.lang.NullPointerException
    at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.getChannelNumber(AutorecoveringChannel.java:49)
    at ExtendedExceptionHandler.handleChannelRecoveryException(ExtendedExceptionHandler.java:118)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverChannels(AutorecoveringConnection.java:403)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:363)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:48)
    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.shutdownCompleted(AutorecoveringConnection.java:345)
    at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:75)
    at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:572)
    at java.lang.Thread.run(Thread.java:662)

ExtendedExceptionHandler here is just extension of DefaultExceptionHandler which writes data to log file instead of system.err. Connection is established to remote RabbitMQ cluster. Here's connection factory setup:

< bean id="connectionFactory" class="com.rabbitmq.client.ConnectionFactory">
        < property name="requestedHeartbeat" value="5" />
        < property name="connectionTimeout" value="5000" />
        < property name="automaticRecoveryEnabled" value="true" />
        < property name="exceptionHandler" ref="extendedExceptionHandler"/>
    < /bean>

I had no luck on trying to reproduce such issue on test environment, but it keeps popping up on our production environment from time to time. Can you provide some information on how it's possible that channelNumber is null during connection recovery?

**Comment by michaelklishin** [comment]
```
java.net.SocketException: Connection reset
```

means the server refused TCP connection. Also, `3.3.x` versions no longer get any updates. Please upgrade to 3.5.6 (at least the client).
