### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by younes88** [rabbitmq/rabbitmq-java-client#275]
java.lang.OutOfMemoryError: Could not allocate JNI Env
at java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:1063)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
at com.rabbitmq.client.impl.ConsumerWorkService.addWork(SourceFile:77)
at com.rabbitmq.client.impl.ConsumerDispatcher.execute(SourceFile:208)
at com.rabbitmq.client.impl.ConsumerDispatcher.handleShutdownSignal(SourceFile:168)
at com.rabbitmq.client.impl.ChannelN.broadcastShutdownSignal(SourceFile:258)
at com.rabbitmq.client.impl.ChannelN.finishProcessShutdownSignal(SourceFile:276)
at com.rabbitmq.client.impl.ChannelN.processShutdownSignal(SourceFile:292)
at com.rabbitmq.client.impl.ChannelManager.handleSignal(SourceFile:96)
at com.rabbitmq.client.impl.AMQConnection.finishShutdown(SourceFile:741)
at com.rabbitmq.client.impl.AMQConnection.shutdown(SourceFile:714)
at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(SourceFile:571)
at java.lang.Thread.run(Thread.java:818)

**Comment by acogoluegnes** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
In this case the VM cannot allocate a new thread. Either increase the OS limit on the maximum number of kernel threads or see Consumer Work Pool and Thread Factories [in the docs](https://www.rabbitmq.com/api-guide.html) for how to make the client use fewer threads as the number of connections grows.
