### ISSUE TITLE
4.1 client seem to retry failed connection via IPv6

### ISSUE THREAD

**Issue by dimas** [rabbitmq/rabbitmq-java-client#283]
We have something called DumbAmqpServer used in our integration tests where we verify client behaves as expected. That class accepts AMQP connection over SSL on port 30012, reads protocol header and then just writes back 
```java
private final byte[] PROTOCOL_HEADER = {'A', 'M', 'Q', 'P', 0, 0, 9, 1};
```
to simulate situation that server did not like the protocol version and rejected connection. (However we observe exactly the same behaviour even when DumbAmqpServer just close() s SSL connection immediately after accepting it without reading or writing anything)

So after switching to the version 4.1 of the RabbitMQ client, the integration test broke because it now sees two connection attempts to that server where with 3.x it used to see only one.
From the log of DumbAmqpServer itself, it looks like it receives two connection attempts each time - one for IPv4 address and one for IPv6.

```
2017-05-28 19:32:18,050 DEBUG null     [DumbAmqpServer] c.a.z.h.m.r.DumbAmqpServer Accepted connection /127.0.0.1:56098 => /127.0.0.1:30012
2017-05-28 19:32:18,124 WARN  null     [rabbitmq-nio] c.r.c.i.n.NioLoop Error during reading frames
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:152)
	at java.lang.Thread.run(Thread.java:745)
2017-05-28 19:32:18,125 ERROR null     [rabbitmq-connection-shutdown-amqp://CN=test-client@127.0.0.1:30012/] c.r.c.i.ForgivingExceptionHandler An unexpected connection driver error occured
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:152)
	at java.lang.Thread.run(Thread.java:745)
2017-05-28 19:32:18,126 DEBUG null     [DumbAmqpServer] c.a.z.h.m.r.DumbAmqpServer Accepted connection /0:0:0:0:0:0:0:1:50498 => /0:0:0:0:0:0:0:1:30012
2017-05-28 19:32:18,203 WARN  null     [rabbitmq-nio] c.r.c.i.n.NioLoop Error during reading frames
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:152)
	at java.lang.Thread.run(Thread.java:745)
2017-05-28 19:32:18,204 ERROR null     [rabbitmq-connection-shutdown-amqp://CN=test-client@0:0:0:0:0:0:0:1:30012/] c.r.c.i.ForgivingExceptionHandler An unexpected connection driver error occured
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:152)
	at java.lang.Thread.run(Thread.java:745)
```

The 3.x version of the client only attempts IPv4 connection on the same machine.

I cannot seem to find any mention of that change in behaviour in the documentation.
We probably can do a simple workaround in out tests by binding DumbAmqpServer to IPv4 address only but still it feels like a not-exactly-right behaviour change. JFYI, we call
```java
        factory.useNio();
        factory.setAutomaticRecoveryEnabled(false);
```
when configuring factory. So I am not sure why client should be doing these retries at all - a failed connection is a failed connection. I can in theory understand IPv6 connection attempt if IPv4 failed completely - like no connection could be established at all. But IPv4 connection was properly established and some handshake happened, it is just that the server refused to speak to the client claiming protocol version was bad. Does not seem like a justification for retrying the same server over IPv6....

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
I actually strongly suspect it's due to the fact that connection recovery is enabled by default. Anyhow, a traffic dump will make it clear what exactly the client is doing.

Some users will disagree about the "a failed connection is a failed connection" argument and would expect the client to retry.

Lastly, you can limit your JVM to only use/prefer IPv4 via a property (java.net.preferIPv4Stack = true), which sounds very doable in an integration tests environment.

**Comment by dimas** [comment]
@michaelklishin , I hardly can see how this issue is "a question". I am reporting undocumented (as far) as I can see change of behaviour in the client. 

> I actually strongly suspect it's due to the fact that connection recovery is enabled by default

As I said, we have:
```java
factory.setAutomaticRecoveryEnabled(false);
```
in the code.
I can take a packet capture but as I said, it is SSL so payload won't be visible. What do you want to see there? The DumbAmqpServer can log anything as it sees the entire decrypted stream. As far as I can see, client just sends the same AMQP 0x00 0x00 0x09 0x01 protocol header as DumbAmqpServer uses to reply back. As connection is terminated at that stage, there is no real recovery of exchanges or anything like that.

> Some users will disagree about the "a failed connection is a failed connection" argument and would expect the client to retry.

Again, that could make sense if server was not reachable via IPv4. But it was, the port was open and client received a valid AMQP reply.

PS: I am not looking for workarounds for the problem with our test. I can perfectly find one myself. (specifying broker address as "127.0.0.1" does the trick and has fewer consequences than preferIPv4Stack). I am just reporting you that new version of client behaves differently and that "some people" may not expect it too.

Cheers

**Comment by michaelklishin** [comment]
@dimas I really don't have much to add to https://github.com/rabbitmq/rabbitmq-java-client/issues/283#issuecomment-304532381.

What I am looking to see in the dump is what *exactly* the client is doing and the response receives both at the TCP and AMQP 0-9-1 level.

Thanks for reporting your observations. This is mailing list material as far as our team is concerned.

**Comment by michaelklishin** [comment]
Wireshark can decrypt captured traffic as long as you can provide it with the private key. I'm not sure if exported frames would still be encrypted but they can be exported as text.

Alternatively we could work with any other way of reproducing, e.g. with `netcat`, but since we don't have access to your test suite or the "DumbAmqpServer", there isn't much for us to work with.

Another potentially important observation is that your client uses NIO and 3.x client versions don't support NIO at all. Therefore this is not really an apples-to-apples comparison.

I can go on but don't see any further need to justify that this issue is far from obvious and could use some extra investigation before any conclusions are made => this is mailing list material.

**Comment by acogoluegnes** [comment]
@dimas provided a test case: https://github.com/dimas/rabbitmq-java-client-issue-283

On a MacBook with IPv6 enabled, with Java client 3.6.6:

```
2017-05-29 14:50:07,716 INFO  [main] DumbAmqpServer Started server on port 30012
2017-05-29 14:50:07,735 DEBUG [DumbAmqpServer] DumbAmqpServer Accepted connection /127.0.0.1:49286 => /127.0.0.1:30012
2017-05-29 14:50:07,746 ERROR [main] Test Unexpected exception
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:354)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:886)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:839)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:797)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:960)
	at Test.main(Test.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:372)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:298)
	... 10 common frames omitted
Caused by: com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:173)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:110)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:146)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:553)
	at java.lang.Thread.run(Thread.java:745)
```

On a MacBook with IPv6 enabled, with Java client 4.1.0:
```
2017-05-29 14:51:33,808 INFO  [main] DumbAmqpServer Started server on port 30012
2017-05-29 14:51:33,830 DEBUG [DumbAmqpServer] DumbAmqpServer Accepted connection /127.0.0.1:49306 => /127.0.0.1:30012
2017-05-29 14:51:33,843 ERROR [AMQP Connection 127.0.0.1:30012] c.r.c.i.ForgivingExceptionHandler An unexpected connection driver error occured
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:578)
	at java.lang.Thread.run(Thread.java:745)
2017-05-29 14:51:33,846 DEBUG [DumbAmqpServer] DumbAmqpServer Accepted connection /0:0:0:0:0:0:0:1:49307 => /0:0:0:0:0:0:0:1:30012
2017-05-29 14:51:33,846 ERROR [AMQP Connection 0:0:0:0:0:0:0:1:30012] c.r.c.i.ForgivingExceptionHandler An unexpected connection driver error occured
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:578)
	at java.lang.Thread.run(Thread.java:745)
2017-05-29 14:51:33,846 ERROR [main] Test Unexpected exception
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:116)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:112)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:360)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:920)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:870)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:828)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:996)
	at Test.main(Test.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:398)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:304)
	... 10 common frames omitted
Caused by: com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1
	at com.rabbitmq.client.impl.Frame.protocolVersionMismatch(Frame.java:170)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:107)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:578)
	at java.lang.Thread.run(Thread.java:745)
```

So there's indeed a new attempt on the IPv6 address.

**Comment by acogoluegnes** [comment]
OK, found it. Java Client 3.6.x uses ListAddressResolver, which uses a static list of addresses, and Java Client 4.x.x uses DnsRecordIpAddressResolver when only one address is provided (see ConnectionFactory#createAddressResolver).

DnsRecordIpAddressResolver uses InetAddress.getAllByName (i.e. DNS query), that's why it returned both IPv4 and IPv6 addresses. The original idea is from this issue #138.

Note the client loops over the list of addresses returned by the address resolver, even if automatic recovery is disabled, that's why you see a second attempt.

If this behavior bothers you, you can use ConnectionFactory#newConnection(AddressResolver).

Thanks for reporting this.

**Comment by michaelklishin** [comment]
@acogoluegnes in other words, switching the resolver would be sufficient here. I can see how a DNS record aware resolver would be desired by many, in particular those running on PaaS'es such as Cloud Foundry or Heroku.

I suggest that we wait and see if more people get confused by this.

**Comment by acogoluegnes** [comment]
@michaelklishin Sounds good to me.
