### ISSUE TITLE
Close SocketChannel correctly in NIO mode

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#284]

**Comment by michaelklishin** [comment]
We won't be reopening an issue because of a warning that makes no functional difference and for which we have no steps to reproduce. A new issue would be considered **as long as there are steps to reproduce**.

**Comment by al81-ru** [comment]
Hi, I got this error when combining NIO and SSL:
```
ConnectionFactory connectionFactory = new ConnectionFactory();
connectionFactory.setHost("localhost");
connectionFactory.setPort(5671);
connectionFactory.setUsername("admin");
connectionFactory.setPassword("admin");
connectionFactory.setVirtualHost("/");
connectionFactory.useSslProtocol("TLSv1.2");
connectionFactory.useNio();

Connection con = connectionFactory.newConnection();
con.close();
```

warn exception:
```
[main] WARN com.rabbitmq.client.impl.nio.SocketChannelFrameHandler - Error while closing SocketChannel
java.io.IOException: A non-blocking socket operation could not be completed immediately.
	at java.base/sun.nio.ch.SocketDispatcher.close0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.close(SocketDispatcher.java:63)
	at java.base/sun.nio.ch.SocketChannelImpl.kill(SocketChannelImpl.java:907)
	at java.base/sun.nio.ch.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:895)
	at java.base/java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:242)
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:112)
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.close(SocketChannelFrameHandlerState.java:221)
	at com.rabbitmq.client.impl.nio.SocketChannelFrameHandler.close(SocketChannelFrameHandler.java:99)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1132)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1034)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1018)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1010)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.close(AutorecoveringConnection.java:274)
```

**Comment by michaelklishin** [comment]
@al81-ru comments on nearly 3 year old issues is not how issues should be reported. Please put together an executable example (e.g. using [`tls-gen`](https://github.com/michaelklishin/tls-gen)-produced certificates), publish it on GitHub and file a new issue. Note that the exception comes from the connection closure step.

Our team routinely uses the NIO mode in this client via PerfTest and we haven't seen this before. This may be something TLS-specific but the stack trace does not suggest that at all.

We don't have any context (no platform, JVM, RabbitMQ or certificate information), and therefore cannot suggest anything.
We won't guess as guessing is a very time-consuming and expensive way of troubleshooting infrastructure.
