### ISSUE TITLE
java.lang.NoClassDefFoundError: com.rabbitmq.client.impl.AMQChannel$$Lambda$0

### ISSUE THREAD

**Issue by shayan3985** [rabbitmq/rabbitmq-java-client#310]
hello
i  got the following error from this line after i  upgraded rabbitmq library to version 5 

`connection = factory.newConnection();`

`FATAL EXCEPTION: Thread-1669
 Process: com.****, PID: 18398
                                                                java.lang.NoClassDefFoundError: com.rabbitmq.client.impl.AMQChannel$$Lambda$0
                                                                    at com.rabbitmq.client.impl.AMQChannel.enqueueRpc(AMQChannel.java:204)
                                                                    at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:289)
                                                                    at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
                                                                    at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
                                                                    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:944)
                                                                    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:903)
                                                                    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:861)
                                                                    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1013)
                                                                    at com.****.*****.*****.****.lambda$onStartCommand$2$*****(*****.java:130)
                                                                    at com.****.****.service.****$$Lambda$2.run(Unknown Source)
                                                                    at java.lang.Thread.run(Thread.java:818)`

i've changed every callback to lamda btw

every thing worked perfectly in prior version

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
@shayan3985 JDK 8 is now the minimum required version. Java versions older than 8 do not support lambdas. Please take a look at the client's [release notes](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.0.0).

**Comment by shayan3985** [comment]
the problem is  
i'm using gradle 4.2
and java jdk1.8.0_144 which i assume its version 8 


i have this line in my gradle 
` compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`
and my android studio(which is 3.0.0)  is fully supporting lamda

**Comment by michaelklishin** [comment]
@shayan3985 consider providing that kind of information upfront, for this project and others. Compiling your code JDK 8 one thing (and would fail on any earlier version). You must also use JDK 8 when you run your code.

Our team does not use GitHub issues for questions, investigations, RCA and such. Please stick to the mailing list.
