### ISSUE TITLE
When using ConnectionFactory.useNio = true, the system time is adjusted by 1 hour, the MQ connection is disconnected, the connection can not be automatically resumed

### ISSUE THREAD

**Issue by MongoX** [rabbitmq/rabbitmq-java-client#348]
When using ConnectionFactory.useNio = true, the system time is adjusted by 1 hour, the MQ connection 
 is disconnected, the connection can not be automatically resumed。

private void initConnectionFactory(String server) {
        connFactory = new ConnectionFactory();
        connFactory.setUsername(userName);
        connFactory.setPassword(pwd);
        if (vhost != null && !vhost.trim().isEmpty()) {
            connFactory.setVirtualHost(vhost);
        }
        connFactory.setAutomaticRecoveryEnabled(true);  
        connFactory.useNio();
        String[] servers = server.split(",");
        this.address = new ArrayList<Address>();
        for (String s : servers) {
            if (s.contains(":")) {
                String[] k = s.split(":");
                address.add(new Address(k[0], Integer.valueOf(k[1])));
            } else {
                address.add(new Address(s));
            }
        }
    }

exception:

  [rabbitmq-nio] [2018-01-30 18:02:56] [com.rabbitmq.client.impl.ForgivingExceptionHandler] - An unexpected connection driver error occured
  com.rabbitmq.client.MissedHeartbeatException: Heartbeat missing with heartbeat = 60 seconds
	at com.rabbitmq.client.impl.AMQConnection.handleHeartbeatFailure(AMQConnection.java:657)
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:77)
	at java.lang.Thread.run(Thread.java:745)

[rabbitmq-nio] [2018-01-30 18:03:11] [com.rabbitmq.client.impl.ForgivingExceptionHandler] - Caught an exception during connection recovery!
  java.util.concurrent.TimeoutException
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:306)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConnection(AutorecoveringConnection.java:550)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:512)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$2.recoveryCanBegin(AutorecoveringConnection.java:453)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:702)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:696)
	at com.rabbitmq.client.impl.AMQConnection.handleHeartbeatFailure(AMQConnection.java:663)
	at com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:77)
	at java.lang.Thread.run(Thread.java:745)

**Comment by michaelklishin** [comment]
I'm not convinced it's NIO-specific at all. There are two parts of the system that are utterly confused by the time drift and report timeouts: a continuation mechanism in channels and the heartbeat mechanism.

I don't think supporting time drift is a "feature" we'd like to have: in some scenarios we may or may not be able to do anything sensible when time suddenly jumps.
