### ISSUE TITLE
 Error with com.rabbitmq:amqp-client:5.2.0 dependency

### ISSUE THREAD

**Issue by anelfdz** [rabbitmq/rabbitmq-java-client#355]
Hi there!

I want to use RabbitMQ Java Client in my Android app, I added the dependency

`implementation com.rabbitmq:amqp-client:5.2.0`

but when I try to build my project I got the following error:
```
Exception in thread "main" java.lang.TypeNotPresentException: Type io.micrometer.core.instrument.MeterRegistry not present
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:54)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
        at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:399)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
Caused by: java.lang.ClassNotFoundException: Class io.micrometer.core.instrument.MeterRegistry not found
        at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
        ... 14 more
```

This is my build.gradle file

```
apply plugin: 'com.android.application'
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "xxx"
        minSdkVersion 16
        targetSdkVersion 27        
        ...        
    }
    ...    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }    
}
...
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    ...
    // RabbitMQ
    implementation 'com.rabbitmq:amqp-client:5.2.0'
    ...
}
```

How can I solve that issue?

Thanks in advance...

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The Micrometer dependency is not present or cannot be loaded in your Android Studio environment.

**Comment by anelfdz** [comment]
Sorry for publish my question as an issue, but I checked the RabbitMQ .pom file and the Micrometer dependency is in there, but as optional, so I think that if RabbitMQ uses that dependency it can't be optional, so I guess it is an issue.

I added the Micrometer dependency in my build.gradle but I got the same error with another library, so something is wrong with RabbitMQ dependencies.

**Comment by michaelklishin** [comment]
@anelfdz our team does not use GitHub issues for questions. "the same error with another library" is not evidence of a "dependency issue" with this one.

This is the first time someone reported something like this and we don't have enough details to reproduce or evidence to make conclusions. rabbitmq-users is where we collect and hash out such details.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/-DN17_BtRWc).

**Comment by acogoluegnes** [comment]
[Fix](https://groups.google.com/d/msg/rabbitmq-users/-DN17_BtRWc/E7BlBLttBAAJ)
