### ISSUE TITLE
Reconnect after cluster node restart

### ISSUE THREAD

**Issue by tmszdmsk** [rabbitmq/rabbitmq-java-client#358]
Problem
---------
Java RabbitMQ client doesn't reconnect despite having automatic recovery enabled. We have a 3-node cluster. Queue **is not** in HA mode. When node managing the queue goes down for a restart, consumer connection isn't recovered after node becomes available again.

Here is the exception we get:
```
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering consumer amq.ctag-CNP1joDPC-8gExVmVOi9uw: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - home node 'rabbit@hostname' of durable queue 'queue-name' in vhost 'vhost-name' is down or inaccessible, class-id=50, method-id=10)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConsumers(AutorecoveringConnection.java:717)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:546)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:59)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$2.recoveryCanBegin(AutorecoveringConnection.java:474)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:754)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:731)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:615)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - home node 'rabbit@hostname' of durable queue 'queue-name' in vhost 'vhost-name' is down or inaccessible, class-id=50, method-id=10)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:228)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:303)
	at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1261)
	at com.rabbitmq.client.impl.recovery.RecordedConsumer.recover(RecordedConsumer.java:60)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConsumers(AutorecoveringConnection.java:698)
	... 7 common frames omitted
```

and this is how we configure the connection:
```java
    ConnectionFactory factory = new ConnectionFactory();
    factory.setHost(config.getHost());
    factory.setPort(config.getPort());
    factory.setUsername(config.getUser());
    factory.setPassword(config.getPassword());
    factory.setVirtualHost(config.getVHost());
    factory.setAutomaticRecoveryEnabled(true);
    factory.setRequestedHeartbeat(10);
    factory.setExceptionHandler(new StrictExceptionHandler());
```

Versions
---------
* RabbitMQ version: **3.6.11**
* Erlang version: **Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64] [kernel-poll:true]**
* rabbitmq-java-client versions: **4.0.1** and **4.6.0**

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The error messages explain what's going on: a durable non-mirrored queue is unavailable because, well, its hosting node isn't. And thus any operation on it closes the channel. Either make the queue non-durable or use mirroring.
