### ISSUE TITLE
Exception thrown continuously in Android

### ISSUE THREAD

**Issue by LPascual-mk** [rabbitmq/rabbitmq-java-client#402]
Hi,

I have been using RabbitMQ for a project to communicate our server to an Android application. The communication between both entities is correct but in the Android side I see the following error repeated continuously in the Logcat. Has this exception happened to anyone at some point? What may I be doing wrong in my app or server?

 W/System.err:   at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:114)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:291)
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:94)
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:138)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:541)
        at java.lang.Thread.run(Thread.java:764)
    com.rabbitmq.client.ShutdownSignalException: connection error
        at com.rabbitmq.client.QueueingConsumer.handle(QueueingConsumer.java:202)
        at com.rabbitmq.client.QueueingConsumer.nextDelivery(QueueingConsumer.java:219)
        at mk.mk101_sdk.rabbitmq.MessageConsumer$2.run(MessageConsumer.java:161)
    Caused by: java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:114)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
W/System.err:     at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:291)
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:94)
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:138)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:541)
        at java.lang.Thread.run(Thread.java:764)
    com.rabbitmq.client.ShutdownSignalException: connection error
        at com.rabbitmq.client.QueueingConsumer.handle(QueueingConsumer.java:202)
        at com.rabbitmq.client.QueueingConsumer.nextDelivery(QueueingConsumer.java:219)
        **at mk.mk101_sdk.rabbitmq.MessageConsumer$2.run(MessageConsumer.java:161)**
    Caused by: java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:114)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:267)

The piece of code that is causing the issue is the following, you can find the exact line marked with asterisks:
```
private void Consume() {
        mConsumeThread = new Thread() {

            @Override
            public void run() {
                while (Running) {
                    QueueingConsumer.Delivery delivery;

                    try {
                        ****delivery = MySubscription.nextDelivery();****
                        mLastMessage = delivery.getBody();
                        MyRunnable obj = new MyRunnable(mLastMessage);
                        mMessageHandler.post(obj);

                        mModel.basicAck(delivery.getEnvelope().getDeliveryTag(), false);
                    } catch (InterruptedException | IOException | ShutdownSignalException ie) {
                        ie.printStackTrace();
                    }
                }
            }
        };

        mConsumeThread.start();
    }
```

**Comment by acogoluegnes** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by acogoluegnes** [comment]
Don't use `QueueingConsumer`, it's been deprecated and then removed in 5.0. Use `Channel#basicConsume` instead. Please move your question to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users) if you still have problems.

**Comment by LPascual-mk** [comment]
Thank you very much for your quick response. I will move the topic to the link you have shared. Sorry for the inconveniences.
