### ISSUE TITLE
MalformedFrameException: Bad frame end marker 69

### ISSUE THREAD

**Issue by oursy** [rabbitmq/rabbitmq-java-client#697]
Hi , 

There will always be an error in the consumer log

```
2021-07-18 14:52:24.298 ERROR 1 --- [AMQP Connection 172.29.60.38:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured

com.rabbitmq.client.MalformedFrameException: Bad frame end marker: 69
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:117) ~[amqp-client-5.12.0.jar:5.12.0]
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:184) ~[amqp-client-5.12.0.jar:5.12.0]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:665) ~[amqp-client-5.12.0.jar:5.12.0]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
 

Rabbitmq-Server log :

```
2021-07-18 06:52:50.815 [warning] <0.11069.12> closing AMQP connection <0.11069.12> (172.29.60.43:55920 -> 172.21.0.2:5672-rabbitConnectionFactory#5c8d58ed:3, vhost:'/ ', user:'westwell'):
client unexpectedly closed TCP connection
```

Rabbitmq-java-client version :  5.12.0

Rabbitmq Server Nodes :
![image](https://user-images.githubusercontent.com/9456577/126060802-1908b860-dfbf-40d8-ac1f-c214bf880a74.png)

Rabbitmq Server version :

- RabbitMQ 3.8.19
- Erlang 24.0.3

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
