### ISSUE TITLE
ClassCastException while waiting for RPC response

### ISSUE THREAD

**Issue by mgrafl** [rabbitmq/rabbitmq-java-client#708]
In rare cases, the RabbitMQ Java Client misinterprets another frame as RPC response, causing the following stack trace: 

```
java.lang.ClassCastException: class com.rabbitmq.client.impl.AMQImpl$Queue$BindOk cannot be cast to class com.rabbitmq.client.impl.AMQImpl$Basic$ConsumeOk (com.rabbitmq.client.impl.AMQImpl$Queue$BindOk and com.rabbitmq.client.impl.AMQImpl$Basic$ConsumeOk are in unnamed module of loader 'xxxxx.ear' @38b4eb41)
        at xxxxx.ear//com.rabbitmq.client.impl.ChannelN$3.transformReply(ChannelN.java:1359)
        at xxxxx.ear//com.rabbitmq.client.impl.ChannelN$3.transformReply(ChannelN.java:1356)
        at xxxxx.ear//com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.handleCommand(AMQChannel.java:486)
        at xxxxx.ear//com.rabbitmq.client.impl.RpcContinuationRpcWrapper.complete(RpcContinuationRpcWrapper.java:38)
        at xxxxx.ear//com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:200)
        at xxxxx.ear//com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
        at xxxxx.ear//com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739)
        at xxxxx.ear//com.rabbitmq.client.impl.AMQConnection.handleReadFrame(AMQConnection.java:688)
        at xxxxx.ear//com.rabbitmq.client.impl.nio.NioLoop.run(NioLoop.java:160)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
``` 

The exception occurred during auto-recovery. I suspect some kind of race condition for the frames being handled, that the client expected an RPC response but got a frame from auto-recovery. The exception was only observed once. 

The problem appears similar to an already fixed issue: #290. 
A similar problem was also reported on [stackoverflow: Spring RabbitMQ - Getting ClassCastException in MessageListener](https://stackoverflow.com/questions/58337193/spring-rabbitmq-getting-classcastexception-in-messagelistener).

### System information: 
RabbitMQ Java Client version: 5.12.0 on Java 11 on CentOS 7
RabbitMQ Server version: RabbitMQ 3.8.16 on Erlang 23.2.4 on CentOS 7

### Additional information: 
Server logs: 
```
2021-10-05 14:43:17.227 [info] <0.15739.170> accepting AMQP connection <0.15739.170> (xxxxxx:43514 -> xxxxxx:5671)
2021-10-05 14:43:17.234 [info] <0.15739.170> Connection <0.15739.170> (xxxxxx:43514 -> xxxxxx:5671) has a client-provided name: xxxxxx
2021-10-05 14:43:17.238 [info] <0.15739.170> connection <0.15739.170> (xxxxxx:43514 -> xxxxxx:5671 - xxxxxx): user 'xxx' authenticated and granted access to vhost 'xxx'
2021-10-05 14:43:17.277 [info] <0.15786.170> Mirrored queue 'xxxx' in vhost 'xxx': Adding mirror on node rabbit@xxx: <17325.10.179>
2021-10-05 14:43:17.320 [warning] <0.15739.170> closing AMQP connection <0.15739.170> (xxxxxx:43514 -> xxxxxx:5671 - xxxxxx, vhost: 'xxx', user: 'xxx'):
client unexpectedly closed TCP connection
2021-10-05 14:43:17.321 [info] <0.15776.170> Closing all channels from connection 'xxxxxx:43514 -> xxxxxx:5671' because it has been closed
```

Exactly two minutes later, the auto-recovery had a timeout for consumer recovery: 
```
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering consumer amq.ctag--0758cgT1fMMGxV-2uREFQ: Continuation call for method #method<basic.consume>(ticket=0, queue=xxxxx, consumer-tag=amq.ctag--0758cgT1fMMGxV-2uREFQ, no-local=false, no-ack=true, exclusive=false, nowait=false, arguments=null) on channel AMQChannel(amqp://xxx@xxxxxx:5671/xxx,1) (#1) timed out
        at xxxxx.ear//com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConsumer(AutorecoveringConnection.java:859)
        at xxxxx.ear//com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$groupEntitiesByChannel$16(AutorecoveringConnection.java:943)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.glassfish.javax.enterprise.concurrent//org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
Caused by: com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<basic.consume>(ticket=0, queue=xxxxx, consumer-tag=amq.ctag--0758cgT1fMMGxV-2uREFQ, no-local=false, no-ack=true, exclusive=false, nowait=false, arguments=null) on channel AMQChannel(amqp://xxx@xxxxxx:5671/xxx,1) (#1) timed out
        at xxxxx.ear//com.rabbitmq.client.impl.AMQChannel.wrapTimeoutException(AMQChannel.java:313)
        at xxxxx.ear//com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1380)
        at xxxxx.ear//com.rabbitmq.client.impl.recovery.RecordedConsumer.recover(RecordedConsumer.java:60)
        at xxxxx.ear//com.rabbitmq.client.impl.recovery.AutorecoveringConnection.wrapRetryIfNecessary(AutorecoveringConnection.java:866)
        at xxxxx.ear//com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConsumer(AutorecoveringConnection.java:835)
        ... 8 more
Caused by: java.util.concurrent.TimeoutException
        at xxxxx.ear//com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
        at xxxxx.ear//com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
        at xxxxx.ear//com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
        at xxxxx.ear//com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
        at xxxxx.ear//com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1378)
        ... 11 more
```

**Comment by michaelklishin** [comment]
This suggests that a pending continuation was expecting a different frame that never arrived, presumably because the connection was already effectively down. In that case, besides using a lower timeout, there aren't that many options we can consider here. Force clearing all continuations can be dangerous, although IIRC Bunny tries to do something like that.

You are welcome to investigate the codebase to see what our options are.

**Comment by michaelklishin** [comment]
> AMQP 0.9.1 does not have a correlation ID to match requests and responses

at the frame level, that is.

**Comment by mgrafl** [comment]
One additional note for future reference: The aforementioned `SSLProtocolException`, which triggered the auto-recovery in the first place ([comment-937487576](https://github.com/rabbitmq/rabbitmq-java-client/issues/708#issuecomment-937487576)), was caused by #700.
