### ISSUE TITLE
unsigned 8 bit number field type seems not to be supported

### ISSUE THREAD

**Issue by ByteAlex** [rabbitmq/rabbitmq-java-client#713]
Library version: 5.13.1

Error Log:
`
01:01:34.258 [AMQP Connection XXXXXXXX:XXXX] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occurred
com.rabbitmq.client.MalformedFrameException: Unrecognised type in table
	at com.rabbitmq.client.impl.ValueReader.readFieldValue(ValueReader.java:214)
	at com.rabbitmq.client.impl.ValueReader.readTable(ValueReader.java:150)
	at com.rabbitmq.client.impl.ValueReader.readTable(ValueReader.java:252)
	at com.rabbitmq.client.impl.ContentHeaderPropertyReader.readTable(ContentHeaderPropertyReader.java:108)
	at com.rabbitmq.client.AMQP$BasicProperties.<init>(AMQP.java:1716)
	at com.rabbitmq.client.impl.AMQImpl.readContentHeaderFrom(AMQImpl.java:4845)
	at com.rabbitmq.client.impl.CommandAssembler.consumeHeaderFrame(CommandAssembler.java:101)
	at com.rabbitmq.client.impl.CommandAssembler.handleFrame(CommandAssembler.java:158)
	at com.rabbitmq.client.impl.AMQCommand.handleFrame(AMQCommand.java:89)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:112)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:739)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:666)
	at java.base/java.lang.Thread.run(Thread.java:832)
`

Steps to reproduce:
Dispatch an amqp payload with table type `B`: unsigned 8 bit number
Try to receive said payload with the java client.

Expected result:
Client parses the payload successfully.

Actual result:
Client fails to parse the result.

Current workaround:
Instead of using u8, I'm sending a u16.

Suggested fix:
Append type `B` to the switch in ValueReader.java:161

Thanks for reading!

**Comment by michaelklishin** [comment]
@ByteAlex if a type is missing for over a decade and no one complains, I'd say it's a `wontfix` but you are welcome to submit a PR.

**Comment by michaelklishin** [comment]
Before you do anything, please carefully go through [this part of the AMQP 0-9-1 Errata document](https://www.rabbitmq.com/amqp-0-9-1-errata.html#section_3).

**Comment by ByteAlex** [comment]
Thank you for your guidance here. After reading the mentioned document it seems like the `B` type *should* be implemented by RabbitMQ. I'll open a PR to add this; it should be fairly simple!
